package com.groupe1.collabdev_api.entities.enums;

public enum DomaineIdeeProjet {
    INTELLIGENCE_ARTIFICIELLE,
    DEVELOPPEMENT_WEB,
    DEVELOPPEMENT_MOBILE,
    CYBERSECURITE,
    BASES_DE_DONNEES,
    DEVOPS,
    CLOUD_COMPUTING,
    INTERNET_DES_OBJETS,
    REALITE_VIRTUELLE,
    REALITE_AUGMENTEE,
    JEUX_VIDEO,
    AUTOMATISATION,
    BLOCKCHAIN,
    SYSTEMES_EMBARQUES,
    BIG_DATA,
    ANALYSE_DE_DONNEES,
    RESEAUX,
    SYSTEMES_D_INFORMATION,
    INFORMATIQUE_DECISIONNELLE,
    ACCESSIBILITE_NUMERIQUE,
    SANTE_NUMERIQUE,
    EDUCATION_NUMERIQUE,
    ROBOTIQUE,
    GREEN_IT
}
